services:
  monimage:
    build: .
    networks:
      - default
      - webproxy
    labels:
      - "traefik.enable=true"

      # Règle corrigée pour accepter le domaine avec ET sans 'www'
      - "traefik.http.routers.monimage.rule=Host(`angular01.enclume-numerique.com`, `www.angular01.enclume-numerique.com`)"
      - "traefik.http.routers.monimage.entrypoints=websecure"
      - "traefik.http.routers.monimage.tls=true"
      # On dit au routeur d'utiliser notre résolveur 'le' pour obtenir le certificat
      - "traefik.http.routers.monimage.tls.certresolver=le"

      - "traefik.http.services.monimage.loadbalancer.server.port=80"

      # Redirection HTTP -> HTTPS (cette partie reste la même)
      - "traefik.http.routers.monimage-http.rule=Host(`angular01.enclume-numerique.com`, `www.angular01.enclume-numerique.com`)"
      - "traefik.http.routers.monimage-http.entrypoints=web"
      - "traefik.http.routers.monimage-http.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"

networks:
  webproxy:
    external: true
