services:
  monimage:
    build: .
    networks:
      - default
      - webproxy
    labels:
      - "traefik.enable=true"

      # Règle corrigée avec l'opérateur OU (||)
      - "traefik.http.routers.monimage.rule=Host(`angular01.enclume-numerique.com`) || Host(`www.angular01.enclume-numerique.com`)"
      - "traefik.http.routers.monimage.entrypoints=websecure"
      - "traefik.http.routers.monimage.tls=true"
      - "traefik.http.routers.monimage.tls.certresolver=le"

      - "traefik.http.services.monimage.loadbalancer.server.port=80"

      # Règle de redirection également corrigée
      - "traefik.http.routers.monimage-http.rule=Host(`angular01.enclume-numerique.com`) || Host(`www.angular01.enclume-numerique.com`)"
      - "traefik.http.routers.monimage-http.entrypoints=web"
      - "traefik.http.routers.monimage-http.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"

networks:
  webproxy:
    external: true
